### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by UlysseCoteAllard** [ozanciga/dirt-t#1]
Hi, 
I will most likely use part of your implementation in a publication, how should I cite your work?
Thanks in advance!

**Comment by ozanciga** [comment]
hey thank you for that. i did some digging and got a doi for this repository: https://www.doi2bib.org/bib/10.5281/zenodo.3496237

although i prefer: 
@misc{https://doi.org/10.5281/zenodo.3496237,
  doi = {10.5281/ZENODO.3496237},
  url = {https://zenodo.org/record/3496237},
  author = {{Ozan Ciga}},
  title = {Github repository for Pytorch implementation of A DIRT-T Approach to Unsupervised Domain Adaptation},
  publisher = {Zenodo},
  year = {2019}
}

you can use this if you like.
